### ISSUE TITLE
DareBlopy windows

### ISSUE THREAD

**Issue by chinasilva** [podgorskiy/DareBlopy#2]
i can't pip it in windows,hot to repair it,and i user setup.py file,also some errors

**Comment by podgorskiy** [comment]
Fixed in https://github.com/podgorskiy/DareBlopy/commit/66480d08a517a0ec525e66f85f3f66171ac8b763 https://github.com/podgorskiy/DareBlopy/commit/33dd413e488ddcdcd227b988f607529f80261d4c https://github.com/podgorskiy/DareBlopy/commit/548fc099f9172cb76f3f2e69a1d9d101045b4835  https://github.com/podgorskiy/DareBlopy/commit/03b61b484b772056e99a74a13646b1a8057f6163

Uploaded package to pypi. Now you can do `pip install dareblopy` on Windows

Python2.7 version is not working properly, but I'm not going to fix that.
